### ISSUE TITLE
프로젝트 피드백

### ISSUE THREAD

**Issue by knunu** [HyungcheolSim/voyageBlog#2]
과제 구현하시느라 고생 많으셨습니다. 제가 피드백 드리는 프로젝트 중에 가장 완성도가 높은 프로젝트인 것 같습니다. 크게 피드백 드릴만한 부분이 없지만, 좀 더 챙기면 좋을만한 부분을 피드백 드리자면 다음과 같습니다. 

---

* API 명세서는 postman의 api documentation tool을 사용하신 것으로 보이네요. postman을 활용하시는 것도 좋지만, 이후에 controller 쪽 코드가 변경되면 다시 또 업데이트를 하셔야 할텐데요. 코드레벨에서 swagger를 활용한 API 문서를 만드는 방식을 활용하시면 그런 번거로움 없이 바로 업데이트 되서 api 문서에 반영이 되니 다음에 한번 적용해보시는걸 권장합니다.
* use case diagram (UML), ERD, 그리고 DDL 까지 작성해주셨네요. 잘 작성해주셔서 프로젝트를 파악하는데 많은 도움이 됐습니다. 근데 use case diagram의 경우 sequence diagram이나 flow chart의 형식으로 구성하는게 일반적입니다. 현재 작성해주신 다이어그램에서는 기능들이 어떤식으로 제공되고 연관되어 있는지만 보이고, 어떤 흐름으로 서비스가 제공되는지 알기가 조금 어렵네요. 이 부분은 제가 위에서 드린 키워드들(sequence diagram, flow chart)로 검색해보시면 좋은 예시가 나오니 참고하셔서 반영해보시면 좋을 것 같습니다. ERD는 user와 comment, post가 1:1 관계인지 1:n, n:n 관계인지 안나와 있어서 조금 아쉽네요. intellij에서 자체적으로 제공해주는 기능을 활용하시는건 좋습니다만 이게 전달해야되는 필수적인 정보들이 누락되어 있는지는 않은지 확인해주셔야 합니다.
* 코드 레벨에서 피드백을 드릴만한 부분은 없습니다. 잘 구현해주셨습니다. 앞으로도 이런 방식으로 열심히 학습하시고, 잘 구현해주시면 될 것 같습니다.

**Comment by HyungcheolSim** [comment]
네 피드백 감사합니다! 추후 피드백 반영해서 개선 진행하겠습니다!!

**Comment by HyungcheolSim** [comment]
피드백 체크 리스트로 정리->4주차 과제와 함꼐 리팩토링할 예정
- [ ] swagger 적용
- [x] 현재 다이어그램을 관계가 보이는 다이어그램으로 변경하기
       프로젝트 재실행(db 수정사항 반영) -> workbench에서 erd 확인
- [x] UML sequence diagram이나 flow chart로 작성해보기
