### ISSUE TITLE
프로젝트 질문

### ISSUE THREAD

**Issue by HyungcheolSim** [HyungcheolSim/voyageBlog#9]
## 개인 질문 
> cascade 적용을 위해 기존 관계를 양방향 관계로 변경해줘야 한다고 자료를 확인했습니다. 이떄 관계를 통해서 데이터를 확인하고 싶어서가 아니라 삭제를 위해서 관계를 양방향으로 바꾸는 건 바람직하지 않다고 느껴지는데,  db에서 직접 관계 설정해주는 방법은 어떤지 궁금합니다. 이런 경우 어떤 식으로 구현을 결정하는 게 좋은지 궁금합니다.

**Comment by knunu** [comment]
기존에 만들어져 있는 ER에서 삭제를 위해 양방향 관계로 만드는 것은 저도 그리 권장하진 않습니다.
직접 DML을 조작하는 코드들, 이를테면 user - item list의 1:n 관계를 가지고 있을 때 user를 제거할 때 해당되는 item list들을 따로 지워주고 user를 지워주는것도 나쁘지 않습니다.
생각하신대로 구현해주시고, 이에 대한 테스트 코드도 같이 구현해주시면 충분히 괜찮을 것 같습니다.
